config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"
  get 'mypage' => "home#mypage"
  resources :posts, only: [:create, :show, :index] do
    resources :metoos, only: [:create]
    post "echo", to: "echos#post_echo_toggle"
    post "comment_echo", to: "echos#comment_echo_toggle"

  end
  resources :missions, only: [:create]
  resources :echos, only: [:create]
  resources :comments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_many :echos
end

app/models/echo.rb
class Echo < ApplicationRecord
  belongs_to :post
  belongs_to :comment
  belongs_to :user
end

app/models/metoo.rb
class Metoo < ApplicationRecord
  belongs_to :user
end

app/models/mission.rb
class Mission < ApplicationRecord
  has_and_belongs_to_many :users
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :echos
  has_many :comments
  has_many :metoos
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_and_belongs_to_many :missions
  has_many :echos
  has_many :comments
  def is_post_echo?(post)
    Echo.find_by(user_id: self.id,post_id: post.id).present?
  end
  def is_comment_echo?(post)
    Comment.find_by(user_id: self.id,post_id: post.id).present?
  end
  def is_metoo?(post)
    Metoo.find_by(user_id: self.id,post_id: post.id).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/echos_controller.rb
class EchosController < ApplicationController
  def post_echo_toggle
    @echo = Echo.find_by(user_id: current_user.id, post_id: params[:post_id])
    if @echo.nil?
      Echo.create(user_id: current_user.id, post_id: params[:post_id])
    else
      @echo.destroy
    end
  end
  def comment_echo_toggle
    @echo = Echo.find_by(user_id: current_user.id, post_id: params[:post_id],comment_id: parmas[:comment_id])
    if @echo.nil?
      Echo.create(user_id: current_user.id, post_id: params[:post_id],comment_id: parmas[:comment_id])
    else
      @echo.destroy
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @post = Post.new();
    @all_missions = Mission.all
    @user_missions = current_user.missions
  end
end

app/controllers/metoos_controller.rb
class MetoosController < ApplicationController
  def create
    @metoo = Metoo.find_by(user_id: current_user.id, post_id: params[:post_id])
    if @metoo.nil?
      Metoo.create(user_id: current_user.id, post_id: params[:post_id])
    else
      @metoo.destroy
    end
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  def create
    @mission = Mission.create()
    current_user.missions << @mission
    redirect_to root_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @post.save
    redirect_to root_path
  end
  def index
  end  
  def show
    @post = Post.find(params[:id])
  end
  private
  def post_params
    params.require(:post).permit(:content,:photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/echos_helper.rb
module EchosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/metoos_helper.rb
module MetoosHelper
end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<div class="row">
  <div class="col"></div>
  <div class="col" style="margin:12px">
    <%= image_tag 'letter.png' %>
  </div>
  <div class="col"></div>
</div>
<div class="row" style="background-color:#ff0056;padding:20px;">
  <div class="col-3">
    <%= image_tag 'profile.png',style: 'border-radius:80px' %>
  </div>
  <div class="col">
    <%=simple_form_for(@post) do |f| %>
      <div class="form-group">
        <%= f.input :content, input_html: { class: 'form-control' }, label: false, placeholder: '당신의 마음을 움직여 만들어낸 울림을 기록해주세요.' %>
      </div>
      <div class="form-group">
        <label for="file-input" style="float:right;">
          <i class="fa fa-camera" aria-hidden="true">리뷰사진</i>
        </label>
        <%= f.file_field :photo, style: 'display: none', id: "file-input" %>
      </div>
      <%= f.button :submit, class: 'btn btn-default',style: 'background-color:black;color:white',value: '기록하기'%>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-3" style="margin:50px;background-color:#ff0056;max-width:110px;min-height:110px;border-radius:20px;">
    <%=link_to(missions_path,method: :post) do %>
      <i class="fa fa-hand-paper-o fa-5x" aria-hidden="true" style="margin-top:15px;"></i>
    <% end %>
  </div>
  <div class="col">
    <div class="" style="margin:30px;font-size:20px;" >
      <p style="font-size:25px;font-weight:bold">오늘의 미션!</p>
      만나는 사람들과 반갑게 인사할때 </br>
      버튼 누르기!
    </div>
    <div class="" style="float:left;font-weight:bold">
      오늘 전체 미션 달성수 : <%=@all_missions.size %>
    </div>
    <div class="" style="float:right;font-weight:bold">
      나의 미션 달성수 : <%=@user_missions.size %>
    </div>
  </div>
</div>

<div class="">
  <p>Beautiful Story</p>
  <iframe width="47%" height="200px;" src="https://www.youtube.com/embed/dLHi2FNets4?modestbranding=1&loop=1&enablejsapi=1"
  frameborder="0" frameborder="0" allowfullscreen></iframe>
  <iframe style="float:right" width="47%" height="200px;" src="https://www.youtube.com/embed/zlGVxRnKv1k?modestbranding=1&loop=1&enablejsapi=1"
  frameborder="0" frameborder="0" allowfullscreen></iframe>
</div>




<script type="text/javascript">
$('form input').keydown(function (e) {
    if (e.keyCode == 13) {
        var inputs = $(this).parents("form").eq(0).find(":input");
        if (inputs[inputs.index(this) + 1] != null) {
            inputs[inputs.index(this) + 1].focus();
        }else{
          input[inputs.index(this)].submit();
        }
        e.preventDefault();
        return false;
    }
});
</script>

app/views/home/mypage.html.erb
<div class="" style="padding:0;margin:0">
  <%= image_tag 'mypage.png',style: "width:105%;height:auto;padding:0;position:relative;bottom:120px;z-index:-10000;right:14px;" %>
</div>

app/views/layouts/_header.html.erb
<div class="row header">
  <div class="col"></div>
  <div class="col">
    <%= image_tag 'symbol.png',style: "width:80%;hieght:auto" %>
  </div>
  <div class="col"></div>
</div>

app/views/layouts/_navigator.html.erb
<div class="row">
  <div class="col navbar">
    <%= link_to root_path do %>
      <i class="fa fa-home fa-3x" aria-hidden="true"></i>
    <% end %>
  </div>
  <div class="col navbar">
    <%= link_to posts_path do %>
      <i class="fa fa-video-camera fa-3x" aria-hidden="true"></i>
    <% end %>
  </div>
  <div class="col navbar">
    <%= link_to post_path(1) do %>
      <i class="fa fa-book fa-3x" aria-hidden="true"></i>
    <% end %>
  </div>
  <div class="col navbar">
    <%= link_to root_path do %>
      <i class="fa fa-map fa-3x" aria-hidden="true"></i>
    <% end %>
  </div>
  <div class="col navbar">
    <%= link_to mypage_path do %>
      <i class="fa fa-user-circle fa-3x" aria-hidden="true"></i>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InvisibleBeauty</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="row">
      <div class="col"></div>
      <div class="col-5">
        <%= render 'layouts/header' %>
        <%= yield %>
        <%= render 'layouts/navigator' %>
      </div>
      <div class="col"></div>
      </div>
  </body>
</html>

app/views/posts/index.html.erb
<div class="row">
  <div class="col"></div>
  <div class="col" style="margin:12px">
    <%= image_tag 'letter.png' %>
  </div>
  <div class="col"></div>
</div>
<h3 style="text-align:center;background-color:#ff0056;padding-top:10px;padding-bottom:10px;">당신에게 울림을 줄 Beautiful Story</h3>
<iframe width="100%" height="300px;" src="https://www.youtube.com/embed/_28CfzvgbF0?modestbranding=1&loop=1&enablejsapi=1"
frameborder="0" frameborder="0" allowfullscreen></iframe>
<iframe width="100%" height="300px;" src="https://www.youtube.com/embed/JM_rxkAQGF8?modestbranding=1&loop=1&enablejsapi=1"
frameborder="0" frameborder="0" allowfullscreen></iframe>
<iframe width="100%" height="300px;" src="https://www.youtube.com/embed/SIpD6LI2rGg?modestbranding=1&loop=1&enablejsapi=1"
frameborder="0" frameborder="0" allowfullscreen></iframe>
<iframe width="100%" height="300px;" src="https://www.youtube.com/embed/o4QgtoBb9CI?modestbranding=1&loop=1&enablejsapi=1"
frameborder="0" frameborder="0" allowfullscreen></iframe>
<iframe width="100%" height="300px;" src="https://www.youtube.com/embed/9npfWzdiRm0?modestbranding=1&loop=1&enablejsapi=1"
frameborder="0" frameborder="0" allowfullscreen></iframe>

app/views/posts/show.html.erb
<div class="" style="">
  <%= image_tag 'around.jpeg',style: "position:relative;top:-150px;left:20px;z-index:-10000" %>
</div>